# Numpy
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python
## What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [4]:
import numpy as np

In [6]:
lst=[1,2,3,4,5]
print(type(lst))

<class 'list'>


In [9]:
arr=np.array(lst)
arr


array([1, 2, 3, 4, 5])

In [30]:
print(arr.sum())

15


In [11]:
print(type(arr))

<class 'numpy.ndarray'>


In [14]:
arr.shape#one dimensional array

(5,)

In [15]:
arr*3

array([ 3,  6,  9, 12, 15])

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
a=arr*3
b=arr*4
c=arr*5

In [20]:
#multidimensional array
md=np.array([a,b,c])
md

array([[ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [22]:
md.shape#row by column

(3, 5)

In [31]:
md.sum()

180

In [32]:
md.reshape(5,3)

array([[ 3,  6,  9],
       [12, 15,  4],
       [ 8, 12, 16],
       [20,  5, 10],
       [15, 20, 25]])

In [33]:
md

array([[ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [34]:
md.reshape(3,5,1)

array([[[ 3],
        [ 6],
        [ 9],
        [12],
        [15]],

       [[ 4],
        [ 8],
        [12],
        [16],
        [20]],

       [[ 5],
        [10],
        [15],
        [20],
        [25]]])

## indexing and slicing

In [35]:
md

array([[ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [42]:
md.shape

(3, 5)

In [36]:
md[2]

array([ 5, 10, 15, 20, 25])

In [37]:
md[2][3]

20

In [39]:
md[:,:]#[row,column]=[3,5]

array([[ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [43]:
md[0:2,1:3]

array([[ 6,  9],
       [ 8, 12]])

In [44]:
md[1:,2:]

array([[12, 16, 20],
       [15, 20, 25]])

In [45]:
md[1:3,2:5]

array([[12, 16, 20],
       [15, 20, 25]])

In [46]:
arr

array([1, 2, 3, 4, 5])

In [47]:
arr[2:]=100

In [48]:
arr

array([  1,   2, 100, 100, 100])

In [49]:
#some condition used in exploratory data analysis
arr>3

array([False, False,  True,  True,  True])

In [50]:
arr[arr>3]#to find which holds true for the condition

array([100, 100, 100])

In [51]:
#creating the array

In [60]:
a=np.arange(0,10)#arange([start,] stop[, step,], dtype=None)


In [61]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
b=np.arange(2,20,dtype=float)
b

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19.])

In [66]:
b=a.reshape(2,5)
c=a.reshape(2,5)*5

In [68]:
b*c#elementwise product

array([[  0,   5,  20,  45,  80],
       [125, 180, 245, 320, 405]])

In [74]:
b.dot(c.reshape(5,2))#dot product

array([[300, 350],
       [800, 975]])

In [77]:
d=np.ones((4,5))
d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [81]:
e=np.ones((4,5),dtype=int)
e

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [84]:
np.random.rand(3,3)

array([[0.24955321, 0.45252544, 0.95818602],
       [0.96369253, 0.78467144, 0.90961164],
       [0.63990589, 0.74451804, 0.33935551]])

In [93]:
np.random.randn(3,3)#Return a sample (or samples) from the "standard normal" distribution.


array([[-0.82168664, -1.06948625, -0.41130798],
       [-1.71337166, -1.96278266, -1.13379465],
       [-1.39744723, -0.8004995 ,  2.10524414]])

In [89]:
#randint(low, high=None, size=None, dtype=int)

np.random.randint(3,100,8)

array([48, 95, 89, 58,  8, 53, 41, 49])

In [90]:
np.random.randint(3,100,8).reshape(2,4)

array([[53, 68, 46, 70],
       [99, 50, 91, 33]])

In [92]:
np.random.sample((1,4))

array([[0.75824406, 0.45769497, 0.4248675 , 0.59889856]])